name: release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: read

jobs:
  publish-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Cosign
        uses: sigstore/cosign-installer@9614fae9e5c5eddabb09f90a270fcb487c9f7149 # v3.3.0
      - name: Setup Timoni
        uses: ./actions/setup
      - name: Login to GHCR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push cert-manager module
        run: |
          timoni mod push ./modules/cert-manager oci://ghcr.io/nalum/timoni/cert-manager \
          -v ${GITHUB_REF_NAME#v} --latest \
          -a 'org.opencontainers.image.licenses=Apache-2.0' \
          -a 'org.opencontainers.image.source=https://github.com/nalum/cert-manager-module'  \
          -a 'org.opencontainers.image.description=A timoni.sh module for cert-manager.' \
          -a 'org.opencontainers.image.documentation=https://github.com/nalum/cert-manager-module'  \
          --sign cosign
